name: setup-vcpkg

description: Bootstraps vcpkg and sets up binary caching with NuGet

runs: 
  using: composite
  steps:
    - name: Bootstrap vcpkg
      env:
        EXT: ${{ case(runner.os == 'Windows', '.bat', '.sh') }}
      shell: bash
      run: ./vcpkg/bootstrap-vcpkg$EXT

    - name: Install Mono (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends -y mono-devel

    # - name: Install NuGet (Linux)
    #   if: runner.os == 'Linux'
    #   uses: nuget/setup-nuget@fd55a6f3b34392fa83fde1454582407d8c714123 # v4.0

    - name: Set up NuGet Credentials
      shell: 'bash'
      env:
        MONO: ${{ case(runner.os == 'Windows', '', 'mono') }}
      run: |
        $MONO `./vcpkg/vcpkg fetch nuget | tail -n 1` \
          sources add \
          -source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
          -storepasswordincleartext \
          -name "GitHub" \
          -username "${{ github.repository_owner }}" \
          -password "${{ github.token }}"
        $MONO `./vcpkg/vcpkg fetch nuget | tail -n 1` \
          setapikey "${{ github.token }}" \
          -source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
