name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-test:
    name: Build+Test
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            preset: msvc-debug
          - os: ubuntu-latest
            preset: gcc-debug
          - os: ubuntu-latest
            preset: clang-debug
    runs-on: ${{ matrix.os }}
    env:
      CMAKE_COMPILE_WARNING_AS_ERROR: "ON"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      # Set up x64 developer command prompt on Windows
      # Important: this must be done before run-vcpkg because both set VCPKG_ROOT and we want run-vcpkg's
      - uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1.13.0
        if: runner.os == 'Windows'
        with:
          arch: x64
      - uses: lukka/get-cmake@fffaaafeea488556c2c12dad60690008bc1caacb # v4.4.2
      - uses: lukka/run-vcpkg@b1a0dd252f06b9e25b3c022a9a03bd7a427fb6a2 # v11.6
      - run: cmake --preset ${{ matrix.preset }}
      - run: cmake --build --preset ${{ matrix.preset }}
      - run: ctest --preset ${{ matrix.preset }}
      - run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "::error::Uncommitted changes or untracked files detected!"
            git status
            exit 1
          fi

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: lukka/get-cmake@fffaaafeea488556c2c12dad60690008bc1caacb # v4.4.2
      - uses: lukka/run-vcpkg@b1a0dd252f06b9e25b3c022a9a03bd7a427fb6a2 # v11.6
      - run: cmake --preset clang-debug
      # TODO: Run clang-tidy with pinned version

  format:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      # TODO: Run "clang-format --dry-run --Werror" with pinned version

  # Branch ruleset check
  ci-ok:
    if: always()
    needs: [build-test, lint, format]
    runs-on: ubuntu-latest
    steps:
      - if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: exit 1
